package com.wmm.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MechanicTileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMechanicTileAllPropertiesEquals(MechanicTile expected, MechanicTile actual) {
        assertMechanicTileAutoGeneratedPropertiesEquals(expected, actual);
        assertMechanicTileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMechanicTileAllUpdatablePropertiesEquals(MechanicTile expected, MechanicTile actual) {
        assertMechanicTileUpdatableFieldsEquals(expected, actual);
        assertMechanicTileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMechanicTileAutoGeneratedPropertiesEquals(MechanicTile expected, MechanicTile actual) {
        assertThat(actual)
            .as("Verify MechanicTile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMechanicTileUpdatableFieldsEquals(MechanicTile expected, MechanicTile actual) {
        assertThat(actual)
            .as("Verify MechanicTile relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getComment()).as("check comment").isEqualTo(expected.getComment()))
            .satisfies(a -> assertThat(a.getMaterialCode()).as("check materialCode").isEqualTo(expected.getMaterialCode()))
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMechanicTileUpdatableRelationshipsEquals(MechanicTile expected, MechanicTile actual) {
        assertThat(actual)
            .as("Verify MechanicTile relationships")
            .satisfies(a -> assertThat(a.getCategories()).as("check categories").isEqualTo(expected.getCategories()))
            .satisfies(a -> assertThat(a.getWarehouses()).as("check warehouses").isEqualTo(expected.getWarehouses()));
    }
}
