services:
  - type: web
    name: sapport-pl
    env: node          # ⬅️ вместо env: java
    plan: free
    buildCommand: >
      bash -lc 'export JAVA_HOME=/usr/lib/jvm/java-17 && export PATH=$JAVA_HOME/bin:$PATH &&
      ./mvnw -Pprod -DskipTests clean verify'
    startCommand: >
      bash -lc 'export JAVA_HOME=/usr/lib/jvm/java-17 && export PATH=$JAVA_HOME/bin:$PATH &&
      export SPRING_DATASOURCE_URL="jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}" &&
      export SPRING_DATASOURCE_USERNAME="${DB_USER}" &&
      export SPRING_DATASOURCE_PASSWORD="${DB_PASSWORD}" &&
      java -Dserver.port=$PORT -jar target/*.jar'
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JHIPSTER_SLEEP
        value: "10"
      - key: DB_HOST
        fromDatabase: { name: sapport-pl-db, property: host }
      - key: DB_PORT
        fromDatabase: { name: sapport-pl-db, property: port }
      - key: DB_NAME
        fromDatabase: { name: sapport-pl-db, property: database }
      - key: DB_USER
        fromDatabase: { name: sapport-pl-db, property: user }
      - key: DB_PASSWORD
        fromDatabase: { name: sapport-pl-db, property: password }

databases:
  - name: sapport-pl-db
    plan: free
    databaseName: wmmapp
    user: wmmapp
